#!/usr/bin/env python
"""
Script pour ajouter le symbole $ aux labels des champs monétaires dans forms.py
"""

# Liste des champs qui représentent des montants en argent
MONEY_FIELDS = [
    'solde_crtg_operante', 'revenus', 'depenses_deductibles', 'depenses_non_deductibles',
    'salaire_client', 'salaire_conjoint', 'salaire_employe', 'dpa_federale', 'dpa_provinciale',
    'solde_imrtd_non_determines', 'solde_imrtd_determines', 'solde_cdc', 'solde_crtg_gestion',
    'paqc_reportee', 'perte_capitale', 'pbr_actions_ordinaires', 'capital_verse',
    'actions_dividendes_discretionnaires', 'cout_par_jour', 'revenus_emploi',
    'revenus_entreprise', 'montant', 'rentes_revenus_rrq_rpc', 'revenu_admissible',
    'revenus_dividendes', 'dividende_ordinaire', 'dividende_determine', 'dividende_capital',
    'cotisation_totale', 'cotisation_employeur', 'transfert_initial_pd', 'transfert_initial_cva',
    'transfert_initial_cd', 'solde_immobilise', 'solde_cva', 'cotisation_regulieres',
    'cotisation_service_passe', 'cotisation_volontaire_additionnelles', 'rente',
    'ajustements_frais_annuels', 'revenu_pension_1', 'revenu_pension_2', 'cotisation_employe',
    'facteur_equivalence', 'cotisation_annuelle', 'budget_annuel_permanent',
    'budget_extraordinaire', 'capital_deces', 'cout_base_rajuste', 'valeur_rachat',
    'prime_annuelle', 'droits_reer_inutilises', 'cotisations_reer_non_deduites',
    'droits_celi_inutilises', 'droits_celiapp', 'fe_pd_annee_precedente', 'ecgc_passe',
    'impot_minimum_remplacement_federal', 'impot_minimum_remplacement_provincial',
    'revenus_nets_federaux_passe', 'solde_crtg', 'seuil_cdc', 'frais_cdc',
    'juste_valeur_marchande', 'pbr_total', 'pbr_terrain', 'fnacc', 'emprunts', 'dons',
    'au_deces', 'solde_pret', 'versement_mensuel', 'net_avant_interet', 'indexation',
    'entree_fonds_imposable', 'entree_fonds_non_imposable', 'sortie_fonds_deductible',
    'sortie_fonds_non_deductible'
]

# Mapping des noms de champs vers des labels français avec $
LABELS = {
    'solde_crtg_operante': 'Solde CRTG opérante ($)',
    'revenus': 'Revenus ($)',
    'depenses_deductibles': 'Dépenses déductibles ($)',
    'depenses_non_deductibles': 'Dépenses non déductibles ($)',
    'salaire_client': 'Salaire client ($)',
    'salaire_conjoint': 'Salaire conjoint ($)',
    'salaire_employe': 'Salaire employé ($)',
    'dpa_federale': 'DPA fédérale ($)',
    'dpa_provinciale': 'DPA provinciale ($)',
    'solde_imrtd_non_determines': 'Solde IMRTD non déterminés ($)',
    'solde_imrtd_determines': 'Solde IMRTD déterminés ($)',
    'solde_cdc': 'Solde CDC ($)',
    'solde_crtg_gestion': 'Solde CRTG gestion ($)',
    'paqc_reportee': 'PAQC reportée ($)',
    'perte_capitale': 'Perte capitale ($)',
    'pbr_actions_ordinaires': 'PBR actions ordinaires ($)',
    'capital_verse': 'Capital versé ($)',
    'actions_dividendes_discretionnaires': 'Actions dividendes discrétionnaires ($)',
    'cout_par_jour': 'Coût par jour ($)',
    'revenus_emploi': 'Revenus d\'emploi ($)',
    'revenus_entreprise': 'Revenus d\'entreprise ($)',
    'montant': 'Montant ($)',
    'rentes_revenus_rrq_rpc': 'Rentes revenus RRQ/RPC ($)',
    'revenu_admissible': 'Revenu admissible ($)',
    'revenus_dividendes': 'Revenus dividendes ($)',
    'dividende_ordinaire': 'Dividende ordinaire ($)',
    'dividende_determine': 'Dividende déterminé ($)',
    'dividende_capital': 'Dividende capital ($)',
    'cotisation_totale': 'Cotisation totale ($)',
    'cotisation_employeur': 'Cotisation employeur ($)',
    'transfert_initial_pd': 'Transfert initial PD ($)',
    'transfert_initial_cva': 'Transfert initial CVA ($)',
    'transfert_initial_cd': 'Transfert initial CD ($)',
    'solde_immobilise': 'Solde immobilisé ($)',
    'solde_cva': 'Solde CVA ($)',
    'cotisation_regulieres': 'Cotisations régulières ($)',
    'cotisation_service_passe': 'Cotisation service passé ($)',
    'cotisation_volontaire_additionnelles': 'Cotisations volontaires additionnelles ($)',
    'rente': 'Rente ($)',
    'ajustements_frais_annuels': 'Ajustements frais annuels ($)',
    'revenu_pension_1': 'Revenu pension 1 ($)',
    'revenu_pension_2': 'Revenu pension 2 ($)',
    'cotisation_employe': 'Cotisation employé ($)',
    'facteur_equivalence': 'Facteur d\'équivalence ($)',
    'cotisation_annuelle': 'Cotisation annuelle ($)',
    'budget_annuel_permanent': 'Budget annuel permanent ($)',
    'budget_extraordinaire': 'Budget extraordinaire ($)',
    'capital_deces': 'Capital décès ($)',
    'cout_base_rajuste': 'Coût de base rajusté ($)',
    'valeur_rachat': 'Valeur de rachat ($)',
    'prime_annuelle': 'Prime annuelle ($)',
    'droits_reer_inutilises': 'Droits REER inutilisés ($)',
    'cotisations_reer_non_deduites': 'Cotisations REER non déduites ($)',
    'droits_celi_inutilises': 'Droits CELI inutilisés ($)',
    'droits_celiapp': 'Droits CELIAPP ($)',
    'fe_pd_annee_precedente': 'FE PD année précédente ($)',
    'ecgc_passe': 'ECGC passé ($)',
    'impot_minimum_remplacement_federal': 'Impôt minimum remplacement fédéral ($)',
    'impot_minimum_remplacement_provincial': 'Impôt minimum remplacement provincial ($)',
    'revenus_nets_federaux_passe': 'Revenus nets fédéraux passé ($)',
    'solde_crtg': 'Solde CRTG ($)',
    'seuil_cdc': 'Seuil CDC ($)',
    'frais_cdc': 'Frais CDC ($)',
    'juste_valeur_marchande': 'Juste valeur marchande ($)',
    'pbr_total': 'PBR total ($)',
    'pbr_terrain': 'PBR terrain ($)',
    'fnacc': 'FNACC ($)',
    'emprunts': 'Emprunts ($)',
    'dons': 'Dons ($)',
    'au_deces': 'Au décès ($)',
    'solde_pret': 'Solde prêt ($)',
    'versement_mensuel': 'Versement mensuel ($)',
    'net_avant_interet': 'Net avant intérêt ($)',
    'indexation': 'Indexation ($)',
    'entree_fonds_imposable': 'Entrée fonds imposable ($)',
    'entree_fonds_non_imposable': 'Entrée fonds non imposable ($)',
    'sortie_fonds_deductible': 'Sortie fonds déductible ($)',
    'sortie_fonds_non_deductible': 'Sortie fonds non déductible ($)',
}

print("Liste des champs monétaires et leurs labels:")
print("=" * 80)
for field, label in sorted(LABELS.items()):
    print(f"{field:40} -> {label}")
print("\nTotal:", len(LABELS), "champs monétaires")
