# Generated by Django 4.2.25 on 2025-10-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_societe_actions_dividendes_discretionnaires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurancevie',
            name='personne_assuree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assurances_assuree', to='core.client'),
        ),
        migrations.AlterField(
            model_name='assurancevie',
            name='personne_assuree_externe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assurancevie',
            name='preneur_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assurances_preneur', to='core.client'),
        ),
        migrations.AlterField(
            model_name='assurancevie',
            name='preneur_externe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assurancevie',
            name='preneur_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assurances_preneur', to='core.societe'),
        ),
    ]
